# Generated by Django 6.0.1 on 2026-02-16 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_category_name_orderitem_product_image_and_more'),
        ('users', '0004_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sellerprofile')),
            ],
        ),
    ]
