# Generated by Django 6.0.1 on 2026-02-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_payment_id'),
        ('users', '0004_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellertransaction',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='sellertransaction',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellertransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Release'), ('available', 'Available to Withdraw'), ('paid', 'Paid to Seller'), ('cancelled', 'Cancelled/Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellertransaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withdrawn_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.sellerprofile')),
            ],
        ),
    ]
