# Generated by Django 6.0.1 on 2026-02-18 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_sellertransaction_release_date'),
        ('users', '0004_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sellerprofile')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sellerwallet')),
            ],
        ),
    ]
