# Generated by Django 6.0.1 on 2026-02-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_sellerwithdrawrequest'),
        ('users', '0004_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerwithdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid to Seller'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='sellerwithdrawrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('seller',), name='unique_pending_withdraw_per_seller'),
        ),
    ]
