# Generated by Django 6.0.1 on 2026-01-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
