# Generated by Django 6.0.1 on 2026-02-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied')], default='pending', max_length=10),
        ),
    ]
